Lesson 13
JoannaBiegala/invoicing-system-joanna-biegala pull request #23
Opened 2022-10-12 14:01 UTC by KacperKropidlowski

2022-10-12 15:43 UTC, JoannaBiegala approved these changes, later dismissed

2022-10-12 16:50 UTC, JoannaBiegala approved these changes, later dismissed

2022-10-12 18:49 UTC, mwrobert approved these changes, later dismissed

2022-10-12 18:59 UTC, JoannaBiegala submitted a review, later dismissed

2022-10-13 14:32 UTC, patryk-stepniak requested changes

2022-10-13 14:32 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoice/model/Vat.java
> +@Table(name = "vat")
Ta klasa nie jest encją, więc @Table nic nie daje.

2022-10-13 18:02 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoice/model/Vat.java
> +@Table(name = "vat")
Adnotacja usunięta

2022-10-13 18:21 UTC, mwrobert submitted a review, later dismissed

2022-10-13 18:59 UTC, JoannaBiegala submitted a review, later dismissed

2022-10-13 19:00 UTC, mwrobert approved these changes, later dismissed

2022-10-14 11:44 UTC, patryk-stepniak submitted a review, later dismissed
Super :)
Branch zawiera zmiany z poprzedniego zadania, więc nie mogę go teraz zmergować. Zadanie zaliczam, a branch zmergujcie sami, gdy poprzednie zadanie trafi do mastera.

2022-10-17 14:59 UTC, mwrobert approved these changes

2022-10-17 15:26 UTC, merged