Lesson 15
JoannaBiegala/invoicing-system-joanna-biegala pull request #33
Opened 2022-10-17 09:08 UTC by KacperKropidlowski

2022-10-19 18:03 UTC, mwrobert submitted a review, later dismissed

2022-10-19 20:20 UTC, mwrobert submitted a review, later dismissed

2022-10-20 06:54 UTC, JoannaBiegala approved these changes, later dismissed

2022-10-20 09:59 UTC, patryk-stepniak requested changes
Tradycyjnie: zasięgi :)

Generalnie już bym to odpuścił, bo to mała rzecz, którą można by poprawić w następnym zadaniu, ale zaraz zaczniecie front i o back-endzie zapomnicie na chwilę :)

2022-10-20 09:59 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoice/controller/company/CompanyApi.java
> +  String COMPANIES_ENDPOINT = "/companies";
package-private?

2022-10-20 09:59 UTC, patryk-stepniak commented on src/main/java/pl/futurecollars/invoice/controller/invoice/InvoiceApi.java
> +  String INVOICES_ENDPOINT = "/invoices";
package-private?

2022-10-20 10:59 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoice/controller/company/CompanyApi.java
> +  String COMPANIES_ENDPOINT = "/companies";
Zrefaktoryzowane

2022-10-20 10:59 UTC, KacperKropidlowski commented on src/main/java/pl/futurecollars/invoice/controller/invoice/InvoiceApi.java
> +  String INVOICES_ENDPOINT = "/invoices";
Zrefaktoryzowane

2022-10-20 11:01 UTC, JoannaBiegala approved these changes

2022-10-20 11:04 UTC, mwrobert approved these changes

2022-10-24 09:07 UTC, patryk-stepniak approved these changes

2022-10-24 09:08 UTC, merged