Initialize new Angular project  &   Create a list of companies read from the mock collection
JoannaBiegala/invoicing-system-joanna-biegala pull request #38
Opened 2022-10-20 20:06 UTC by JoannaBiegala

2022-10-21 16:29 UTC, mwrobert approved these changes, later dismissed

2022-10-24 08:31 UTC, KacperKropidlowski submitted a review, later dismissed

2022-10-24 09:35 UTC, patryk-stepniak requested changes
Generalnie: super :)

Prośba o zmianę nazwy CompanyService.ts na company.service.ts - będzie to nazwa analogiczna do pozostałych plików i tak zwykło się nazywać pliki z service'ami.

Zwróćcie proszę uwagę na importy. Czasami używacie apostrofów, a czasami cudzysłowów. Proponuję to uwspólnić to do apostrofów.

2022-10-24 11:54 UTC, KacperKropidlowski approved these changes

2022-10-24 12:19 UTC, mwrobert approved these changes

2022-10-25 07:13 UTC, patryk-stepniak approved these changes

2022-10-25 07:13 UTC, merged